#配置数据源
spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://localhost:3306/ito_school?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: root123456

      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
#jpa
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
     ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    static-path-pattern: /itoschool/floorFile
  resources:
    static-locations: /Users/luona/Documents/api_file/itoschool/floorFile/

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


#  rabbitmq:
#    host: 120.132.99.99
#    port: 8886
#    username: admin
#    password: JldRI059
#    publisher-confirms: true
#    publisher-returns: true
#    template.mandatory: true

#单点登录
bsch:
  sso:
    server-url-prefix: http://sso.bestsch.com
    client-host-url: http://localhost:8080
    allow-headers: all
    allow-origins: all
    url-pattern: /api/*

  open:
    base-host: http://base.bestsch.com
    app-key: 100223
    app-secret: 49a1a92123e746ccbd183e2e653fce0c



#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

#如果生产环境要开启swagger，需要配置请求地址
#springfox:
#  documentation:
#    swagger:
#      v2:
#        host: # 接口域名或外网ip


SERVER_ADDRESS: http://localhost:8080

bsch.open.schbase-host: http://sch.schsoft.cn/
#bsch.open.schbase-host: http://debugsch.hongyucloud.com/
BSCH_SCHBASE_HOST: http://debugsch.hongyucloud.com/
#spring
#
#  spring.rabbitmq.host=127.0.0.1
#  spring.rabbitmq.port=5672
#  spring.rabbitmq.username=guest
#  spring.rabbitmq.password=guest


HONORMEDAL_FILE_PATH: /Users/luona/Documents/api_file/honorFile
HONORMEDAL_FILE_WEB_PATH: /Users/luona/Documents/api_file/honorFile



